using Content.Shared.Imperial.ICCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval._CP14.Options;

[GenerateTypedNameReferences]
public sealed partial class CP14OptionsMenuMainTab : Control
{
    public CP14OptionsMenuMainTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(ICCVars.WaveShaderEnabled, WaveShaderEnabled);

        Control.Initialize();
    }
}
