using Content.Client.Friends;
using Content.Shared.Friends;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Friends.UI;

[GenerateTypedNameReferences]
public sealed partial class FactionGroupPanel : PanelContainer
{
    public Action<FactionMemberGroup, string>? ObjectiveSet;

    public FactionMemberGroup Group;

    public FactionGroupPanel(FactionMemberGroup group, string groupObjective = "")
    {
        RobustXamlLoader.Load(this);

        GroupNamePanel.PanelOverride = new StyleBoxFlat(FriendsSystem.FactionGroups[group].Item1);
        Group = group;
        if (group != FactionMemberGroup.None)
            GroupNameText.Text = FriendsSystem.FactionGroups[group].Item2;

        if (groupObjective == string.Empty)
        {
            ObjectivePanel.Visible = false;
            SetObjectiveButtonText.Text = "Назначить задачу";
        }
        else
        {
            Objective.Text = groupObjective;
            SetObjectiveButtonText.Text = "Изменить";
        }
    }
}
