using Content.Shared.Friends;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Friends.UI;


[GenerateTypedNameReferences]
public sealed partial class FactionMenu : DefaultWindow
{
    public Action<NetEntity, string>? ObjectiveSet;
    public Action<NetEntity, string>? GroupSet;
    public Action<NetEntity>? RemoveButtonPressed;

    public FactionMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Populate(Dictionary<NetEntity, FactionMemberData> data)
    {
        Members.DisposeAllChildren();

        foreach (var item in data)
        {
            var group = item.Value.Group;
            var entry = new FactionMenuEntry(item.Key, item.Value);
            EnsureContainer(group).AddChild(entry);
        }
    }

    private BoxContainer EnsureContainer(FactionMemberGroup group)
    {
        foreach (var item in Members.Children)
        {
            if (item is not FactionGroupPanel panel)
                continue;
            if (panel.Group == group)
                return panel.Box;
        }
        var newPanel = new FactionGroupPanel(group);
        Members.AddChild(newPanel);
        return newPanel.Box;
    }
}
